### ISSUE TITLE
Nuxt.js (fresh install) with pinia bug

### ISSUE THREAD

**Issue by maxdzin** [posva/pinia#748]
### Reproduction

Hi @posva 
I've tried today to create a new fresh new Nuxt.js project and added pinia dependencies to that. And new errors come.
Please, note I've tried both options - to move @pinia/nuxt to the dependencies and then to devDependencies, neither works.
So, can you please point me out what is wrong with that and what should I do to solve those issues?

### Steps to reproduce the behavior

1. Clone repository.
2. Run `npm install`.
3. Run `npm run dev`.
4. See error.

### Expected behavior

The app running correctly without errors.

### Actual behavior

The app won't launch due to errors.

Besides, the bug of build for production that was described in this issue is probably also related to it:
https://github.com/posva/pinia/discussions/747

### Additional information

The error output:
![image](https://user-images.githubusercontent.com/6406412/139053338-67d09e9a-624f-4475-bd86-bc9aa041092c.png)

The minimal repo to reproduce:
https://github.com/spirico/nuxt-pinia-test

**Comment by posva** [comment]
I cloned, did a fresh `yarn install` and the project works perfectly. The error is saying you are missing `@pinia/nuxt`. You can add it with `npm i @pinia/nuxt` if for some reason npm failed to install it.

**Comment by maxdzin** [comment]
Thanks for the quick response.
I've tried another fresh install, the `npm install` is finished without any errors.
The @pinia/nuxt is present in node_modules directory. But the error is the same.
It is used node v14.18.1 and I've tried on npm v6.14.15 first and then also with the latest npm v8.1.1.
The error is the same.
I'll try more with yarn.
But are there some limitations of npm? And can you check it with npm instead of yarn?

**Comment by posva** [comment]
I will try with npm. Try deleting your package lock file and installing again

**Comment by posva** [comment]
It works with `npm` too. I think you really have to regen the lock. I did get this error

```
@nuxt/kit: No matching version found for @nuxt/kit@3.0.0-27255596.0c1860a.
```


but it seems unrelated to Pinia

**Comment by maxdzin** [comment]
I've already tried that and pushed a new `package-lock.json` to the repo. Check that out, please.
As for the `@nuxt/kit` error, it showed this:
```
✖ Nuxt Fatal Error                                      │
npt-app-dev  |    │                                                           │
npt-app-dev  |    │   Error: Cannot find module '@nuxt/kit'                   │
npt-app-dev  |    │   Require stack:                                          │
npt-app-dev  |    │   - /usr/src/app/node_modules/@pinia/nuxt/dist/index.js
```

Maybe it is related to the last noted stack (`/usr/src/app/node_modules/@pinia/nuxt/dist/index.js`)?

**Comment by maxdzin** [comment]
@posva congrats on the v2 release!
Regarding the issue of fresh Nuxt.js setup with `@pinia/nuxt`, I've tried again and seems it keeps throwing the error related to @nuxt/kit.

My steps over it:
1. I just did the creation of a new Nuxt.js app as of official Nuxt documentation.
2. Then I've launched the app by `npm run dev` and it works well without any error.
The error caused from the next stage:
3. I did set up the pinia for that as of docs here:
https://pinia.esm.dev/ssr/nuxt.html
3.1. `npm install pinia @pinia/nuxt @nuxtjs/composition-api` is done without errors.
3.2. added types into tsconfig.json:
`
{
  "types": [
    ...
    "@pinia/nuxt"
  ]
}
`
4. I've tried to launch the app by 'npm run dev' and the same error comes we've discussed above:
`
 ✖ Nuxt Fatal Error                                      │
   │                                                           │
   │   Error: Cannot find module '@nuxt/kit'                   │
   │   Require stack:                                          │
   │   - /usr/src/app/node_modules/@pinia/nuxt/dist/index.js
   `
   
 I would appreciate any help with that since I got stuck with that for a very long time and didn't found the proper solution yet.

The repo of that fresh app is here:
https://github.com/spirico/pinia-nuxt
 
P.S. I've tried to downgrade, reinstall, and also with removing `package-lock.json`, `node_modules`, `.nuxt`, and performing fresh install nether works.
P.P.S. I've also tried to do that with an isolated docker container.
The node version I've tried is latest LTS: v14.18.1
and npm I've tried is v6.14.15 and also tried on the latest v8.1.1.

**Comment by WulfP** [comment]
Same issue for me with Nuxt @ v2.15.8

`npm i @nuxt/kit`

fixed it!

**Comment by maxdzin** [comment]
> Same issue for me with Nuxt @ v2.15.8
> 
> `npm i @nuxt/kit`
> 
> fixed it!

Yes. Thanks!
It was resolved the issue for pinia v2.0.0 and @pinia/nuxt v0.1.0. The development mode works well.

@posva I think it would be nice to have a few words about that in readme of `@pinia/nuxt` probably.

But on the production build there is still the issue mentioned here:
https://github.com/posva/pinia/discussions/747

**Comment by posva** [comment]
You keep pinging me on this but **I still cannot reproduce the error** and already gave it a lot of tries and search. It's probably related to the node, or npm version. `@nuxt/kit` is a dependency of `@pinia/nuxt`, which means it's installed when installing `@pinia/nuxt`. You might need to upgrade node/npm and that is said while installing but it's not directly related to pinia.

Having an issue with the workaround and people being able to comment is preferred to an update to the readme for an edge case that doesn't seem to fully fix the problem anyway (since the build keeps failing for you).

FWIW I have a few examples with different environments setup. This one should be helpful https://github.com/piniajs/example-nuxt-2.

I'm using node 16.12.0 and npm 8.1.0 and the build and dev works. Maybe you are able to reproduce the error there too.

**Comment by maxdzin** [comment]
> You keep pinging me on this but **I still cannot reproduce the error** and already gave it a lot of tries and search. It's probably related to the node, or npm version. `@nuxt/kit` is a dependency of `@pinia/nuxt`, which means it's installed when installing `@pinia/nuxt`. You might need to upgrade node/npm and that is said while installing but it's not directly related to pinia.
> 
> Having an issue with the workaround and people being able to comment is preferred to an update to the readme for an edge case that doesn't seem to fully fix the problem anyway (since the build keeps failing for you).
> 
> FWIW I have a few examples with different environments setup. This one should be helpful https://github.com/piniajs/example-nuxt-2.
> 
> I'm using node 16.12.0 and npm 8.1.0 and the build and dev works. Maybe you are able to reproduce the error there too.

OK. I agree with you and will try with the example you've provided.
Thanks for your help.

**Comment by maxdzin** [comment]
For me, by using node v14.18.1 the issue is still there, but by using node v16.13.0 and npm v8.1.0 the issue is not caused anymore.
Thanks.
